import {
  pgTable,
  uuid,
  varchar,
  timestamp,
  text,
  integer,
  boolean,
  jsonb,
  index,
} from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";
import { organizations } from "./organizations.js";
import { goals } from "./goals.js";

export const importSessions = pgTable(
  "import_sessions",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    organizationId: uuid("organization_id")
      .notNull()
      .references(() => organizations.id, { onDelete: "cascade" }),
    filename: text("filename").notNull(),
    fileSize: integer("file_size"),
    status: text("status").default("uploaded"),
    uploadedBy: text("uploaded_by"),
    uploadedAt: timestamp("uploaded_at").defaultNow(),
    completedAt: timestamp("completed_at"),
    errorMessage: text("error_message"),
    importSummary: jsonb("import_summary"),
    createdAt: timestamp("created_at").defaultNow(),
    updatedAt: timestamp("updated_at")
      .defaultNow()
      .$onUpdate(() => new Date()),
  },
  (table) => [
    index("import_sessions_org_id_idx").on(table.organizationId),
    index("import_sessions_status_idx").on(table.status),
  ],
);

export const stagedGoals = pgTable(
  "staged_goals",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    importSessionId: uuid("import_session_id")
      .notNull()
      .references(() => importSessions.id, { onDelete: "cascade" }),
    rowNumber: integer("row_number").notNull(),
    rawData: jsonb("raw_data").notNull(),
    parsedHierarchy: text("parsed_hierarchy"),
    goalNumber: text("goal_number"),
    title: text("title"),
    description: text("description"),
    level: integer("level"),
    ownerName: text("owner_name"),
    department: text("department"),
    validationStatus: text("validation_status").default("valid"),
    validationMessages: text("validation_messages")
      .array()
      .default(sql`'{}'::text[]`),
    isMapped: boolean("is_mapped").default(false),
    mappedToGoalId: uuid("mapped_to_goal_id").references(() => goals.id, {
      onDelete: "set null",
    }),
    action: text("action").default("create"),
    isAutoGenerated: boolean("is_auto_generated").default(false),
    autoFixSuggestions: jsonb("auto_fix_suggestions").default([]),
    createdAt: timestamp("created_at").defaultNow(),
    updatedAt: timestamp("updated_at")
      .defaultNow()
      .$onUpdate(() => new Date()),
  },
  (table) => [
    index("staged_goals_session_id_idx").on(table.importSessionId),
  ],
);
