import { eq } from "drizzle-orm";
import { db } from "../../lib/db";
import { importSessions, organizations, stagedGoals } from "../../lib/schema/index";
import { requireOrgMember } from "../../lib/middleware/auth";
import { jsonOk, jsonError } from "../../lib/response";

function stagedGoalToSnake(sg: typeof stagedGoals.$inferSelect) {
  return {
    id: sg.id,
    import_session_id: sg.importSessionId,
    row_number: sg.rowNumber,
    raw_data: sg.rawData,
    parsed_hierarchy: sg.parsedHierarchy,
    goal_number: sg.goalNumber,
    title: sg.title,
    description: sg.description,
    level: sg.level,
    owner_name: sg.ownerName,
    department: sg.department,
    validation_status: sg.validationStatus,
    validation_messages: sg.validationMessages,
    is_mapped: sg.isMapped,
    mapped_to_goal_id: sg.mappedToGoalId,
    action: sg.action,
    is_auto_generated: sg.isAutoGenerated,
    auto_fix_suggestions: sg.autoFixSuggestions,
    created_at: sg.createdAt,
    updated_at: sg.updatedAt,
  };
}

/**
 * POST /api/imports/autofix/apply
 * Apply a single auto-fix (insert placeholder goal). Requires auth.
 */
export async function POST(req: Request) {
  try {
    const body = await req.json();
    const { session_id, goal_number, title, level, owner_name, department } =
      body;

    if (!session_id) {
      return jsonError("session_id is required", 400);
    }
    if (!goal_number) {
      return jsonError("goal_number is required", 400);
    }
    if (!title) {
      return jsonError("title is required", 400);
    }
    if (level === undefined || level === null) {
      return jsonError("level is required", 400);
    }

    // Look up session → org for membership check
    const [session] = await db
      .select({ organizationId: importSessions.organizationId })
      .from(importSessions)
      .where(eq(importSessions.id, session_id))
      .limit(1);

    if (!session) return jsonError("Import session not found", 404);

    const [org] = await db
      .select({ slug: organizations.slug })
      .from(organizations)
      .where(eq(organizations.id, session.organizationId))
      .limit(1);

    if (!org) return jsonError("Organization not found", 404);

    await requireOrgMember(req, org.slug, "editor");

    const [created] = await db
      .insert(stagedGoals)
      .values({
        importSessionId: session_id,
        rowNumber: -1,
        rawData: {},
        goalNumber: goal_number,
        title,
        level,
        ownerName: owner_name ?? null,
        department: department ?? null,
        isAutoGenerated: true,
        action: "create",
        validationStatus: "valid",
      })
      .returning();

    return jsonOk(stagedGoalToSnake(created));
  } catch (error) {
    if (error instanceof Response) return error;
    return jsonError(
      error instanceof Error ? error.message : "Internal server error",
      500,
    );
  }
}
