import { db } from "../../lib/db";
import { stagedGoals } from "../../lib/schema/index";
import { requireAuth } from "../../lib/middleware/auth";
import { jsonOk, jsonError } from "../../lib/response";

export const config = { runtime: "edge" };

function stagedGoalToSnake(sg: typeof stagedGoals.$inferSelect) {
  return {
    id: sg.id,
    import_session_id: sg.importSessionId,
    row_number: sg.rowNumber,
    raw_data: sg.rawData,
    parsed_hierarchy: sg.parsedHierarchy,
    goal_number: sg.goalNumber,
    title: sg.title,
    description: sg.description,
    level: sg.level,
    owner_name: sg.ownerName,
    department: sg.department,
    validation_status: sg.validationStatus,
    validation_messages: sg.validationMessages,
    is_mapped: sg.isMapped,
    mapped_to_goal_id: sg.mappedToGoalId,
    action: sg.action,
    is_auto_generated: sg.isAutoGenerated,
    auto_fix_suggestions: sg.autoFixSuggestions,
    created_at: sg.createdAt,
    updated_at: sg.updatedAt,
  };
}

/**
 * POST /api/imports/autofix/bulk
 * Bulk apply auto-fixes. Requires auth.
 */
export async function POST(req: Request) {
  try {
    await requireAuth(req);

    const body = await req.json();
    const { session_id, fixes } = body;

    if (!session_id) {
      return jsonError("session_id is required", 400);
    }
    if (!Array.isArray(fixes) || fixes.length === 0) {
      return jsonError("fixes must be a non-empty array", 400);
    }

    const values = fixes.map(
      (fix: {
        goal_number: string;
        title: string;
        level: number;
        owner_name?: string;
      }) => ({
        importSessionId: session_id,
        rowNumber: -1,
        rawData: {},
        goalNumber: fix.goal_number,
        title: fix.title,
        level: fix.level,
        ownerName: fix.owner_name ?? null,
        isAutoGenerated: true,
        action: "create" as const,
        validationStatus: "valid" as const,
      }),
    );

    const created = await db
      .insert(stagedGoals)
      .values(values)
      .returning();

    return jsonOk(created.map(stagedGoalToSnake));
  } catch (error) {
    if (error instanceof Response) return error;
    return jsonError(
      error instanceof Error ? error.message : "Internal server error",
      500,
    );
  }
}
