import { eq } from "drizzle-orm";
import { db } from "../../../lib/db";
import {
  importSessions,
  stagedGoals,
  stagedMetrics,
} from "../../../lib/schema/index";
import { requireAuth } from "../../../lib/middleware/auth";
import { jsonOk, jsonError } from "../../../lib/response";

export const config = { runtime: "edge" };

function extractSessionId(req: Request): string {
  const segments = new URL(req.url).pathname.split("/");
  // /api/imports/sessions/[id]/stage -> segments[4]
  return segments[4];
}

/**
 * POST /api/imports/sessions/:id/stage
 * Stage parsed data (goals + metrics). Requires auth.
 */
export async function POST(req: Request) {
  try {
    await requireAuth(req);

    const sessionId = extractSessionId(req);

    const [session] = await db
      .select()
      .from(importSessions)
      .where(eq(importSessions.id, sessionId))
      .limit(1);

    if (!session) {
      return jsonError("Import session not found", 404);
    }

    const body = await req.json();
    const { goals: goalsData, metrics: metricsData } = body;

    if (!Array.isArray(goalsData)) {
      return jsonError("goals must be an array", 400);
    }

    let goalsCount = 0;
    let metricsCount = 0;

    // Insert staged goals
    if (goalsData.length > 0) {
      const goalValues = goalsData.map(
        (g: Record<string, unknown>, idx: number) => ({
          importSessionId: sessionId,
          rowNumber: (g.row_number as number) ?? idx + 1,
          rawData: g.raw_data ?? {},
          parsedHierarchy: g.parsed_hierarchy as string | undefined,
          goalNumber: g.goal_number as string | undefined,
          title: g.title as string | undefined,
          description: g.description as string | undefined,
          level: g.level as number | undefined,
          ownerName: g.owner_name as string | undefined,
          department: g.department as string | undefined,
          validationStatus: (g.validation_status as string) ?? "valid",
          validationMessages: (g.validation_messages as string[]) ?? [],
          isMapped: (g.is_mapped as boolean) ?? false,
          mappedToGoalId: g.mapped_to_goal_id as string | undefined,
          action: (g.action as string) ?? "create",
          isAutoGenerated: (g.is_auto_generated as boolean) ?? false,
          autoFixSuggestions: g.auto_fix_suggestions ?? [],
        }),
      );

      await db.insert(stagedGoals).values(goalValues);
      goalsCount = goalValues.length;
    }

    // Insert staged metrics
    if (Array.isArray(metricsData) && metricsData.length > 0) {
      const metricValues = metricsData.map(
        (m: Record<string, unknown>) => ({
          stagedGoalId: m.staged_goal_id as string,
          importSessionId: sessionId,
          metricName: m.metric_name as string,
          measureDescription: m.measure_description as string | undefined,
          metricType: m.metric_type as string | undefined,
          dataSource: m.data_source as string | undefined,
          frequency: m.frequency as string | undefined,
          baselineValue: m.baseline_value as string | undefined,
          timeSeriesData: m.time_series_data ?? null,
          unit: m.unit as string | undefined,
          symbol: m.symbol as string | undefined,
          validationStatus: (m.validation_status as string) ?? "valid",
          validationMessages: (m.validation_messages as string[]) ?? [],
          isMapped: (m.is_mapped as boolean) ?? false,
          mappedToMetricId: m.mapped_to_metric_id as string | undefined,
          action: (m.action as string) ?? "create",
        }),
      );

      await db.insert(stagedMetrics).values(metricValues);
      metricsCount = metricValues.length;
    }

    // Update session status to 'parsed'
    await db
      .update(importSessions)
      .set({ status: "parsed" })
      .where(eq(importSessions.id, sessionId));

    return jsonOk({ goals_count: goalsCount, metrics_count: metricsCount });
  } catch (error) {
    if (error instanceof Response) return error;
    return jsonError(
      error instanceof Error ? error.message : "Internal server error",
      500,
    );
  }
}
