import { eq } from "drizzle-orm";
import { db } from "../../../lib/db.js";
import {
  importSessions,
  organizations,
  stagedGoals,
} from "../../../lib/schema/index.js";
import { requireOrgMember } from "../../../lib/middleware/auth.js";
import { jsonOk, jsonError } from "../../../lib/response.js";

function extractSessionId(req: Request): string {
  const segments = new URL(req.url).pathname.split("/");
  // /api/imports/sessions/[id]/stage -> segments[4]
  return segments[4];
}

/**
 * POST /api/imports/sessions/:id/stage
 * Stage parsed data (goals). Requires auth.
 */
export async function POST(req: Request) {
  try {
    const sessionId = extractSessionId(req);

    const [session] = await db
      .select()
      .from(importSessions)
      .where(eq(importSessions.id, sessionId))
      .limit(1);

    if (!session) {
      return jsonError("Import session not found", 404);
    }

    // Look up org slug for membership check
    const [org] = await db
      .select({ slug: organizations.slug })
      .from(organizations)
      .where(eq(organizations.id, session.organizationId))
      .limit(1);

    if (!org) return jsonError("Organization not found", 404);

    await requireOrgMember(req, org.slug, "editor");

    const body = await req.json();
    const { goals: goalsData } = body;

    if (!Array.isArray(goalsData)) {
      return jsonError("goals must be an array", 400);
    }

    let goalsCount = 0;

    // Insert staged goals
    if (goalsData.length > 0) {
      const goalValues = goalsData.map(
        (g: Record<string, unknown>, idx: number) => ({
          importSessionId: sessionId,
          rowNumber: (g.row_number as number) ?? idx + 1,
          rawData: g.raw_data ?? {},
          parsedHierarchy: g.parsed_hierarchy as string | undefined,
          goalNumber: g.goal_number as string | undefined,
          title: g.title as string | undefined,
          description: g.description as string | undefined,
          level: g.level as number | undefined,
          ownerName: g.owner_name as string | undefined,
          department: g.department as string | undefined,
          validationStatus: (g.validation_status as string) ?? "valid",
          validationMessages: (g.validation_messages as string[]) ?? [],
          isMapped: (g.is_mapped as boolean) ?? false,
          mappedToGoalId: g.mapped_to_goal_id as string | undefined,
          action: (g.action as string) ?? "create",
          isAutoGenerated: (g.is_auto_generated as boolean) ?? false,
          autoFixSuggestions: g.auto_fix_suggestions ?? [],
        }),
      );

      await db
        .insert(stagedGoals)
        .values(goalValues);

      goalsCount = goalValues.length;
    }

    // Update session status to 'parsed'
    await db
      .update(importSessions)
      .set({ status: "parsed" })
      .where(eq(importSessions.id, sessionId));

    return jsonOk({ goals_count: goalsCount });
  } catch (error) {
    if (error instanceof Response) return error;
    return jsonError(
      error instanceof Error ? error.message : "Internal server error",
      500,
    );
  }
}
