import { eq } from "drizzle-orm";
import { db } from "../../../lib/db";
import {
  importSessions,
  organizations,
  stagedGoals,
  stagedMetrics,
} from "../../../lib/schema/index";
import { requireOrgMember } from "../../../lib/middleware/auth";
import { jsonOk, jsonError } from "../../../lib/response";

function stagedGoalToSnake(sg: typeof stagedGoals.$inferSelect) {
  return {
    id: sg.id,
    import_session_id: sg.importSessionId,
    row_number: sg.rowNumber,
    raw_data: sg.rawData,
    parsed_hierarchy: sg.parsedHierarchy,
    goal_number: sg.goalNumber,
    title: sg.title,
    description: sg.description,
    level: sg.level,
    owner_name: sg.ownerName,
    department: sg.department,
    validation_status: sg.validationStatus,
    validation_messages: sg.validationMessages,
    is_mapped: sg.isMapped,
    mapped_to_goal_id: sg.mappedToGoalId,
    action: sg.action,
    is_auto_generated: sg.isAutoGenerated,
    auto_fix_suggestions: sg.autoFixSuggestions,
    created_at: sg.createdAt,
    updated_at: sg.updatedAt,
  };
}

function stagedMetricToSnake(sm: typeof stagedMetrics.$inferSelect) {
  return {
    id: sm.id,
    staged_goal_id: sm.stagedGoalId,
    import_session_id: sm.importSessionId,
    metric_name: sm.metricName,
    measure_description: sm.measureDescription,
    metric_type: sm.metricType,
    data_source: sm.dataSource,
    frequency: sm.frequency,
    baseline_value: sm.baselineValue,
    time_series_data: sm.timeSeriesData,
    unit: sm.unit,
    symbol: sm.symbol,
    validation_status: sm.validationStatus,
    validation_messages: sm.validationMessages,
    is_mapped: sm.isMapped,
    mapped_to_metric_id: sm.mappedToMetricId,
    action: sm.action,
    created_at: sm.createdAt,
    updated_at: sm.updatedAt,
  };
}

function extractSessionId(req: Request): string {
  const segments = new URL(req.url).pathname.split("/");
  // /api/imports/sessions/[id]/staged -> segments[4]
  return segments[4];
}

/**
 * GET /api/imports/sessions/:id/staged
 * Get staged data for a session. Requires auth.
 */
export async function GET(req: Request) {
  try {
    const sessionId = extractSessionId(req);

    const [session] = await db
      .select()
      .from(importSessions)
      .where(eq(importSessions.id, sessionId))
      .limit(1);

    if (!session) {
      return jsonError("Import session not found", 404);
    }

    // Look up org slug for membership check
    const [org] = await db
      .select({ slug: organizations.slug })
      .from(organizations)
      .where(eq(organizations.id, session.organizationId))
      .limit(1);

    if (!org) return jsonError("Organization not found", 404);

    await requireOrgMember(req, org.slug, "viewer");

    const goalsData = await db
      .select()
      .from(stagedGoals)
      .where(eq(stagedGoals.importSessionId, sessionId))
      .orderBy(stagedGoals.rowNumber);

    const metricsData = await db
      .select()
      .from(stagedMetrics)
      .where(eq(stagedMetrics.importSessionId, sessionId));

    return jsonOk({
      goals: goalsData.map(stagedGoalToSnake),
      metrics: metricsData.map(stagedMetricToSnake),
    });
  } catch (error) {
    if (error instanceof Response) return error;
    return jsonError(
      error instanceof Error ? error.message : "Internal server error",
      500,
    );
  }
}
