import { eq } from "drizzle-orm";
import { db } from "@api/lib/db";
import {
  importSessions,
  organizations,
  stagedGoals,
} from "@api/lib/schema/index";
import { requireOrgMember } from "@api/lib/middleware/auth";
import { jsonOk, jsonError } from "@api/lib/response";

function stagedGoalToSnake(sg: typeof stagedGoals.$inferSelect) {
  return {
    id: sg.id,
    import_session_id: sg.importSessionId,
    row_number: sg.rowNumber,
    raw_data: sg.rawData,
    parsed_hierarchy: sg.parsedHierarchy,
    goal_number: sg.goalNumber,
    title: sg.title,
    description: sg.description,
    level: sg.level,
    owner_name: sg.ownerName,
    department: sg.department,
    validation_status: sg.validationStatus,
    validation_messages: sg.validationMessages,
    is_mapped: sg.isMapped,
    mapped_to_goal_id: sg.mappedToGoalId,
    action: sg.action,
    is_auto_generated: sg.isAutoGenerated,
    auto_fix_suggestions: sg.autoFixSuggestions,
    created_at: sg.createdAt,
    updated_at: sg.updatedAt,
  };
}

/**
 * GET /api/imports/sessions/[id]/staged
 * Get staged data for a session. Requires auth.
 */
export async function GET(
  req: Request,
  { params }: { params: Promise<{ id: string }> },
) {
  try {
    const { id: sessionId } = await params;

    const [session] = await db
      .select()
      .from(importSessions)
      .where(eq(importSessions.id, sessionId))
      .limit(1);

    if (!session) {
      return jsonError("Import session not found", 404);
    }

    // Look up org slug for membership check
    const [org] = await db
      .select({ slug: organizations.slug })
      .from(organizations)
      .where(eq(organizations.id, session.organizationId))
      .limit(1);

    if (!org) return jsonError("Organization not found", 404);

    await requireOrgMember(req, org.slug, "viewer");

    const goalsData = await db
      .select()
      .from(stagedGoals)
      .where(eq(stagedGoals.importSessionId, sessionId))
      .orderBy(stagedGoals.rowNumber);

    return jsonOk({
      goals: goalsData.map(stagedGoalToSnake),
    });
  } catch (error) {
    if (error instanceof Response) return error;
    return jsonError(
      error instanceof Error ? error.message : "Internal server error",
      500,
    );
  }
}
