import { eq } from "drizzle-orm";
import { db } from "@api/lib/db";
import { importSessions, organizations, stagedGoals } from "@api/lib/schema/index";
import { requireOrgMember } from "@api/lib/middleware/auth";
import { jsonOk, jsonError } from "@api/lib/response";

function stagedGoalToSnake(sg: typeof stagedGoals.$inferSelect) {
  return {
    id: sg.id,
    import_session_id: sg.importSessionId,
    row_number: sg.rowNumber,
    raw_data: sg.rawData,
    parsed_hierarchy: sg.parsedHierarchy,
    goal_number: sg.goalNumber,
    title: sg.title,
    description: sg.description,
    level: sg.level,
    owner_name: sg.ownerName,
    department: sg.department,
    validation_status: sg.validationStatus,
    validation_messages: sg.validationMessages,
    is_mapped: sg.isMapped,
    mapped_to_goal_id: sg.mappedToGoalId,
    action: sg.action,
    is_auto_generated: sg.isAutoGenerated,
    auto_fix_suggestions: sg.autoFixSuggestions,
    created_at: sg.createdAt,
    updated_at: sg.updatedAt,
  };
}

/**
 * PUT /api/imports/sessions/[id]/staged-goals/[goalId]
 * Update a staged goal. Requires auth.
 */
export async function PUT(
  req: Request,
  { params }: { params: Promise<{ id: string; goalId: string }> },
) {
  try {
    const { goalId } = await params;

    const [existing] = await db
      .select()
      .from(stagedGoals)
      .where(eq(stagedGoals.id, goalId))
      .limit(1);

    if (!existing) {
      return jsonError("Staged goal not found", 404);
    }

    // Look up session → org for membership check
    const [session] = await db
      .select({ organizationId: importSessions.organizationId })
      .from(importSessions)
      .where(eq(importSessions.id, existing.importSessionId))
      .limit(1);

    if (!session) return jsonError("Import session not found", 404);

    const [org] = await db
      .select({ slug: organizations.slug })
      .from(organizations)
      .where(eq(organizations.id, session.organizationId))
      .limit(1);

    if (!org) return jsonError("Organization not found", 404);

    await requireOrgMember(req, org.slug, "editor");

    const body = await req.json();

    const updateData: Record<string, unknown> = {};
    const fieldMap: Record<string, string> = {
      row_number: "rowNumber",
      raw_data: "rawData",
      parsed_hierarchy: "parsedHierarchy",
      goal_number: "goalNumber",
      title: "title",
      description: "description",
      level: "level",
      owner_name: "ownerName",
      department: "department",
      validation_status: "validationStatus",
      validation_messages: "validationMessages",
      is_mapped: "isMapped",
      mapped_to_goal_id: "mappedToGoalId",
      action: "action",
      is_auto_generated: "isAutoGenerated",
      auto_fix_suggestions: "autoFixSuggestions",
    };

    for (const [snakeKey, camelKey] of Object.entries(fieldMap)) {
      if (snakeKey in body) {
        updateData[camelKey] = body[snakeKey];
      }
    }

    if (Object.keys(updateData).length === 0) {
      return jsonError("No valid fields to update", 400);
    }

    const [updated] = await db
      .update(stagedGoals)
      .set(updateData)
      .where(eq(stagedGoals.id, goalId))
      .returning();

    return jsonOk(stagedGoalToSnake(updated));
  } catch (error) {
    if (error instanceof Response) return error;
    return jsonError(
      error instanceof Error ? error.message : "Internal server error",
      500,
    );
  }
}
